name: Tesla Check Bot

on:
  schedule:
    - cron: "0 8 * * *"   # runs every day at 08:00 UTC (~10:00 in Zurich during summer)
  workflow_dispatch:       # allows manual run

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run checker
        run: node check.js
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
